### ISSUE TITLE
cxf  restful怎么客户端朝这个里面加入一个map数据

### ISSUE THREAD

**Issue by yuhao1995213** [majinding/webservice#10]
public void handleMessage(Message message) {
        //获取request。
        //HttpServletRequest request = (HttpServletRequest) message.get(AbstractHTTPDestination.HTTP_REQUEST);
        MetadataMap<String, String> metadataMap = (MetadataMap<String, String>) message.get("jaxrs.template.parameters");
       // List<Header> list = message.getHeaders();

这是我服务端的拦截器代码 能获取到"jaxrs.template.parameters"参数 但是客户端我不知道怎么添加我想要的密码放到"jaxrs.template.parameters"参数里面   好让我在服务端可以取到值
客户端代码如下
      Object ob = bcNamelistClientImportData;
        Map<String, String> map = new HashMap<String, String>();
      
       String responseMessage =  client.create("http://localhost:8081/services/bigClientService")
                .path("bean")
               .accept(MediaType.APPLICATION_JSON)
              .post(ob, String.class);

        System.out.println("responseMessage : " + responseMessage);

**Comment by yuhao1995213** [comment]
请群主大大帮忙看一哈子

**Comment by majinding** [comment]
hi , Please provide the import package , I'll look at the source code later

**Comment by majinding** [comment]
you can try 
- url?test1=xxx
- header.put  test2=yyy

**Comment by majinding** [comment]
Through the following source code, it is difficult to trace to the "jaxrs.template.parameters"  data from where  ? 
![image](https://user-images.githubusercontent.com/2681645/65658171-20e37700-e059-11e9-81aa-1a5cc0e489fd.png)

![image](https://user-images.githubusercontent.com/2681645/65658230-64d67c00-e059-11e9-92ff-3128340b2309.png)


![image](https://user-images.githubusercontent.com/2681645/65658263-8cc5df80-e059-11e9-9734-140061127bf5.png)

![image](https://user-images.githubusercontent.com/2681645/65658287-a2d3a000-e059-11e9-818b-e7f620a5d595.png)

So you can pass the key through the header   
for client code :
```
WebClient.create("http://...")
                        .header("k", "v")
                        .accept(MediaType.APPLICATION_XML)
```

for server code:  
```
list = message.getHeaders();
```

**Comment by majinding** [comment]
Handle non-200 cases 
```
        WebClient webClient = WebClient.create("http://...");
        Response response = webClient.header("k", "v")
                .accept(MediaType.APPLICATION_XML)
                .get();
        response.getStatus();
        response.readEntity(HelloBean.class);
```
