### ISSUE TITLE
Spring boot关于@webservice注解类调用业务层接口回传空指针异常问题

### ISSUE THREAD

**Issue by ldcrwxy** [majinding/webservice#11]
一开始写好一个webservice服务，webservice服务接口的实现类，调用业务层接口失败，实现类中无论怎么调用都无法实现，网上有很多教程，但是对一个初学者来说并不友好，
![X@P10E3P~LSPOL%G3MDFEAC](https://user-images.githubusercontent.com/55872672/65752529-8f9b0000-e13f-11e9-8848-3b6c80b414ec.png)
此图中是我写的一个webservice配置类，接口直接new它的实现类是错误的，应该让Springboot用注入的方式进行管理，提供唯一的入口，以下是修改后的配置类，
![`A8A@Z}E{N5{ZNTQH QPTW](https://user-images.githubusercontent.com/55872672/65752676-d852b900-e13f-11e9-8503-ec110454ed7f.png)

**Comment by ldcrwxy** [comment]
以上是我出现的问题的解决方案（一位大佬告诉我的）；

**Comment by majinding** [comment]
good !!!
