### ISSUE TITLE
新问题加密

### ISSUE THREAD

**Issue by yuhao1995213** [majinding/webservice#12]
![图片](https://user-images.githubusercontent.com/23652415/66445515-a4e62780-ea79-11e9-881e-83b65c0b537c.png)

 Response  response =  client.create("http://localhost:8081/services/bigClientService")
                .path("bean")
                //.header("map",map)
                .accept(MediaType.APPLICATION_JSON)
                .post(bcNamelistClientImportData);
     //   int s = response.getStatus();
        MessageData data = response.readEntity(MessageData.class);

现在我这个bcNamelistClientImportData是实体json通过 rsa加密后的数据 那么我服务端还能接受到吗
 @POST
    @Path("/bean")
    //@Produces({MediaType.APPLICATION_XML,MediaType.APPLICATION_JSON})
    @Produces(MediaType.APPLICATION_JSON)
    public MessageData addBeanService(BcNamelistClientImportData bcNamelistClientImportData);

或者说我把这个秘钥数据放入head  那我怎么在服务端拦截器里面 把数据解密后传到我的方法里面？

**Comment by majinding** [comment]
请求的时候 post(bcNamelistClientImportData); 这个数据是如何加密的 ?

**Comment by yuhao1995213** [comment]
现在我找到一种方式了 我post里面不穿参数 我把加密后的数据放入到header中去  post不穿参数怎么写？




------------------ 原始邮件 ------------------
发件人: "JingjingMa"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 中午12:24
收件人: "majinding/webservice"<webservice@noreply.github.com>;
抄送: "Fingal Yue"<1325123392@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [majinding/webservice] 新问题加密 (#12)




请求的时候 post(bcNamelistClientImportData); 这个数据是如何加密的 ?

**Comment by majinding** [comment]
这样怕是不妥吧? 最好还是放在body中, header中的数据长度毕竟是有限制的

群里面那个哪个是你呢 ?

**Comment by yuhao1995213** [comment]
但是我放在post里面 我拦截器拿不到数据啊  post里面的数据是直接匹配的接口中的入参  拦截器中就没得数据了好像  我要找一找




------------------ 原始邮件 ------------------
发件人: "JingjingMa"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 下午2:06
收件人: "majinding/webservice"<webservice@noreply.github.com>;
抄送: "Fingal Yue"<1325123392@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [majinding/webservice] 新问题加密 (#12)




这样怕是不妥吧? 最好还是放在body中, header中的数据长度毕竟是有限制的
 
群里面那个哪个是你呢 ?

**Comment by majinding** [comment]
你先琢磨下,我不是很清楚你的服务端编码,有空我远程看下

**Comment by yuhao1995213** [comment]
嗯嗯  现在问题就是 如果 传post 的 话 我再拦截器中找不到post里面的数据





------------------ 原始邮件 ------------------
发件人: "JingjingMa"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 下午2:13
收件人: "majinding/webservice"<webservice@noreply.github.com>;
抄送: "Fingal Yue"<1325123392@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [majinding/webservice] 新问题加密 (#12)




你先琢磨下,我不是很清楚你的服务端编码,有空我远程看下

**Comment by yuhao1995213** [comment]
现在我问题解决了 传值的 还有一个问题 就是拦截器中数据怎么传到方法里面？




------------------ 原始邮件 ------------------
发件人: "JingjingMa"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 下午2:13
收件人: "majinding/webservice"<webservice@noreply.github.com>;
抄送: "Fingal Yue"<1325123392@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [majinding/webservice] 新问题加密 (#12)




你先琢磨下,我不是很清楚你的服务端编码,有空我远程看下

**Comment by majinding** [comment]
再重新save一次





------------------ 原始邮件 ------------------
发件人: yuhao1995213 <notifications@github.com&gt;
发送时间: 2019年10月9日 16:48
收件人: majinding/webservice <webservice@noreply.github.com&gt;
抄送: JingjingMa <971445096@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[majinding/webservice] 新问题加密 (#12)



现在我问题解决了 传值的 还有一个问题 就是拦截器中数据怎么传到方法里面？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "JingjingMa"<notifications@github.com&gt;; 
 发送时间: 2019年10月9日(星期三) 下午2:13 
 收件人: "majinding/webservice"<webservice@noreply.github.com&gt;; 
 抄送: "Fingal Yue"<1325123392@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
 主题: Re: [majinding/webservice] 新问题加密 (#12) 
 
 
 
 
 你先琢磨下,我不是很清楚你的服务端编码,有空我远程看下

**Comment by yuhao1995213** [comment]
cxf 中
 
AbstractPhaseInterceptor拦截器怎么注入Autowired？  注入都无效 spring没有对类进行扫描   网上的实现一个拦截器 但是那个不兼容
 


 
所以这种方法不行
  

 ------------------ 原始邮件 ------------------
  发件人: "JingjingMa"<notifications@github.com>;
 发送时间: 2019年10月9日(星期三) 晚上6:34
 收件人: "majinding/webservice"<webservice@noreply.github.com>;
 抄送: "Fingal Yue"<1325123392@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [majinding/webservice] 新问题加密 (#12)

 

再重新save一次 





------------------ 原始邮件 ------------------ 
发件人: yuhao1995213 <notifications@github.com&gt; 
发送时间: 2019年10月9日 16:48 
收件人: majinding/webservice <webservice@noreply.github.com&gt; 
抄送: JingjingMa <971445096@qq.com&gt;, Comment <comment@noreply.github.com&gt; 
主题: 回复：[majinding/webservice] 新问题加密 (#12) 



现在我问题解决了 传值的 还有一个问题 就是拦截器中数据怎么传到方法里面？ 




------------------ 原始邮件 ------------------ 
发件人: "JingjingMa"<notifications@github.com&gt;; 
发送时间: 2019年10月9日(星期三) 下午2:13 
收件人: "majinding/webservice"<webservice@noreply.github.com&gt;; 
抄送: "Fingal Yue"<1325123392@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
主题: Re: [majinding/webservice] 新问题加密 (#12) 




你先琢磨下,我不是很清楚你的服务端编码,有空我远程看下

**Comment by yuhao1995213** [comment]
这种老式的接口 soap的要怎么用postman测试&nbsp; 然后就给了一个json实体 代码咋写调用接口

 ------------------ 原始邮件 ------------------
  发件人:&nbsp;"JingjingMa"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年10月9日(星期三) 晚上6:34
 收件人:&nbsp;"majinding/webservice"<webservice@noreply.github.com&gt;;
 抄送:&nbsp;"Fingal Yue"<1325123392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [majinding/webservice] 新问题加密 (#12)

 

再重新save一次 





------------------ 原始邮件 ------------------ 
发件人: yuhao1995213 <notifications@github.com&amp;gt; 
发送时间: 2019年10月9日 16:48 
收件人: majinding/webservice <webservice@noreply.github.com&amp;gt; 
抄送: JingjingMa <971445096@qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt; 
主题: 回复：[majinding/webservice] 新问题加密 (#12) 



现在我问题解决了 传值的 还有一个问题 就是拦截器中数据怎么传到方法里面？ 




------------------ 原始邮件 ------------------ 
发件人: "JingjingMa"<notifications@github.com&amp;gt;; 
发送时间: 2019年10月9日(星期三) 下午2:13 
收件人: "majinding/webservice"<webservice@noreply.github.com&amp;gt;; 
抄送: "Fingal Yue"<1325123392@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
主题: Re: [majinding/webservice] 新问题加密 (#12) 




你先琢磨下,我不是很清楚你的服务端编码,有空我远程看下

**Comment by majinding** [comment]
详细的描述下呗

**Comment by yuhao1995213** [comment]
&nbsp;
  

 

 &nbsp;
 我
 soapui测试的这种数据可以&nbsp; 但是我代码里怎么搞这种格式啊？传进去&nbsp;&nbsp; 图下是代码入参
 
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"JingjingMa"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月20日(星期三) 晚上8:52
 收件人:&nbsp;"majinding/webservice"<webservice@noreply.github.com&gt;;
 抄送:&nbsp;"Fingal Yue"<1325123392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [majinding/webservice] 新问题加密 (#12)

 

 
详细的描述下呗
