### ISSUE TITLE
webservice 如何监控，自动感知webservice 服务上下线，对webservice发布的服务进行监控

### ISSUE THREAD

**Issue by lovo1** [majinding/webservice#13]
webservice 如何监控，自动感知webservice 服务上下线，对webservice发布的服务进行监控，谢谢！

**Comment by majinding** [comment]
推荐在ws服务里增加心跳API
或写个线程监听wsdl文档是否在





------------------ 原始邮件 ------------------
发件人: 00 <notifications@github.com&gt;
发送时间: 2019年10月15日 13:42
收件人: majinding/webservice <webservice@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[majinding/webservice] webservice 如何监控，自动感知webservice 服务上下线，对webservice发布的服务进行监控 (#13)




webservice 如何监控，自动感知webservice 服务上下线，对webservice发布的服务进行监控，谢谢！
