### ISSUE TITLE
CXF生成客户端报错

### ISSUE THREAD

**Issue by wodefengey** [majinding/webservice#16]
在第三方提供wsdl中，存在嵌套import xsd的问题，如下：
![image](https://user-images.githubusercontent.com/22728698/69897852-9a1a8580-138c-11ea-885f-efbac47b3216.png)
例如 wsdl会import  xsd1，xsd2，xsd3，而在xsd2中也会import xsd3.
此时去生成客户端代码报错，如下图：
![image](https://user-images.githubusercontent.com/22728698/69897937-799efb00-138d-11ea-9542-5c08ee915327.png)
请问这有什么解决办法吗？
自己尝试了：
 去掉  -p com.XXX.XXX
 添加 -autoNameResolution
都无效。

**Comment by majinding** [comment]
我这边网上不好, 图片都打不开, 你可以先尝试下使用其他都client方式生成下代码, 看是否可以成功

**Comment by majinding** [comment]
如果是单独使用的wsdl文件来生成代码, 需要将里面引用的文件也改成本地引用
<xsd:import schemaLocation='本地文件路径' ...
