### ISSUE TITLE
在SERVICE  ESB后台注册以后WSDL里面地址问题

### ISSUE THREAD

**Issue by fanencai** [majinding/webservice#18]
通过ESB注册以后WSDL里面底部的地址域名变成了http://web_esb 而不是自己提供的服务器域名 。
![img](https://user-images.githubusercontent.com/31237111/71240515-4de7b300-2344-11ea-8afe-33330e58ce8f.png)

**Comment by majinding** [comment]
hi 你这个访问地址中间是否过了代理或网关，如果是需要配置proxy host





------------------ 原始邮件 ------------------
发件人: 樊恩材 <notifications@github.com&gt;
发送时间: 2019年12月20日 16:08
收件人: majinding/webservice <webservice@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[majinding/webservice] 在SERVICE  ESB后台注册以后WSDL里面地址问题 (#18)





 通过ESB注册以后WSDL里面底部的地址域名变成了http://web_esb 而不是自己提供的服务器域名 。

**Comment by fanencai** [comment]
访问地址通过了代理，是否需要在服务器HOST文件里配置地址域名？

**Comment by majinding** [comment]
需要在代理转发时把header中的host包裹上，


改机器host应该没有作用，可以试试看





------------------ 原始邮件 ------------------
发件人: 樊恩材 <notifications@github.com&gt;
发送时间: 2019年12月23日 08:29
收件人: majinding/webservice <webservice@noreply.github.com&gt;
抄送: JingjingMa <971445096@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[majinding/webservice] 在SERVICE  ESB后台注册以后WSDL里面地址问题 (#18)




访问地址通过了代理，是否需要在服务器HOST文件里配置地址域名？

**Comment by fanencai** [comment]
怎么把header中的主机包裹上？才接触ESB不太熟，注册接口时通过Oracle Service Bu控制台注册的。

**Comment by im-not-a-programmer** [comment]
你好 你可以添加你的好友请教一些问题吗
