### ISSUE TITLE
你好 你可以添加你的好友请教一些问题吗

### ISSUE THREAD

**Issue by BelenLuo-tech** [majinding/webservice#19]
需要在代理转发时把header中的host包裹上，

改机器host应该没有作用，可以试试看

------------------ 原始邮件 ------------------
发件人: 樊恩材 <notifications@github.com&gt;
发送时间: 2019年12月23日 08:29
收件人: majinding/webservice <webservice@noreply.github.com&gt;
抄送: JingjingMa <971445096@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[majinding/webservice] 在SERVICE  ESB后台注册以后WSDL里面地址问题 (#18)

访问地址通过了代理，是否需要在服务器HOST文件里配置地址域名？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @majinding in https://github.com/majinding/webservice/issues/18#issuecomment-568317296_

**Comment by majinding** [comment]
OK
