### ISSUE TITLE
新手请教大佬，关于服务端修改namespace命名空间的问题

### ISSUE THREAD

**Issue by GodKkkkk** [majinding/webservice#23]
服务端问题。服务端使用axis2发布web项目供客户端调用，客户端使用axis2的rpc方式调用WebService（服务地址 + 命名空间 + 方法名）。现在有需求要求服务端的namespace的命名空间要手动改变，请问有办法能让客户端在不修改原命名空间的情况下，继续调用webservice服务吗？

**Comment by majinding** [comment]
没有办法, rpc方式就是根据namespace来匹配到具体的class+method的, 协议规定,不可更改

**Comment by GodKkkkk** [comment]
好的 谢谢老哥
