### ISSUE TITLE
新手求教webservice

### ISSUE THREAD

**Issue by mayi2018** [majinding/webservice#9]
现在有个需求定义了输入参数，输出参数，要求用webservice实现。可否提供demo，谢谢 ！
例如：输入name，starttime，endtime   ， pushTime 输出 receivedStatus，replyMsg

**Comment by majinding** [comment]
Please see https://github.com/majinding/webservice-demo/tree/master/ws-web-demo/src/main/java/cn/majingjing/tm/ws/web

**Comment by mayi2018** [comment]
好的，多谢！有问题再联系。

**Comment by mayi2018** [comment]
服务器与客户相互调用回执，应该怎么解

**Comment by majinding** [comment]
这真是不知道怎么理解 ? 即时客户端又是服务端 ?
